import Head from "next/head";
import Header from "../components/Header";
export default function Home() {
  return (
    <div>
      <Head>
        <title> HULU Clone Film Uygulaması</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {/*Header buraya gelecek*/}
    <Header/>
    
    {/*Navbar buraya gelecek*/}


    {/*Results buraya gelecek*/}

    </div>
  )
}
