import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>QANDQ Film Uygulaması</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <h1>FİLM UYGULAMASI</h1>
    </div>
  )
}
